project:
  type: book
  output-dir: "../../docs"

book:
  title: "Dynamic Programming Basics"
  subtitle: "Materials Taken from Course 'Foundation of Computational Economics, ANU, 2021'"
  author: "Wenzhi Wang"
  date: today
  chapters:
    - index.qmd
    - 01CakeEating.qmd
    - 02LifeCycle.qmd

format:
  html:
    theme: cosmo



